### ISSUE TITLE
What's this line doing in this repository?

### ISSUE THREAD

**Issue by coretemp** [frankfarrell/terraform-provider-redshift#16]
https://github.com/frankfarrell/terraform-provider-redshift/blob/3ac6faa3aa7369ac7ee20e55943c120d103e5ae2/scripts/gogetcookie.sh#L9

**Comment by frankfarrell** [comment]
There's a template for terraform providers and this is in it: 
https://github.com/search?q=z7s05EYPudQ9qoe6dMVfmAVwgZopEkZBb1a2mA5QtHE&type=Code
Not saying its justified, but its a general issue

**Comment by frankfarrell** [comment]
Please open a PR with the changes, thanks!
