### ISSUE TITLE
#!/bin/bash

### ISSUE THREAD

**Issue by coretemp** [frankfarrell/terraform-provider-redshift#17]
/bin/bash is *not* a part of POSIX.

Use /bin/sh if it a POSIX compliant script otherwise user /usr/bin/env bash.

https://github.com/frankfarrell/terraform-provider-redshift/blob/3ac6faa3aa7369ac7ee20e55943c120d103e5ae2/scripts/gogetcookie.sh#L1

**Comment by coretemp** [comment]
If this script is supposed to be executed on my platform, it won't work. If it isn't clearly mark is as "runs only on hashicorp infrastructure" or some sort.

**Comment by frankfarrell** [comment]
Thats fair enough, fixed
