### ISSUE TITLE
Add support to terraform 0.12

### ISSUE THREAD

**Issue by Mor-Walkme** [frankfarrell/terraform-provider-redshift#28]
Hey,
It would be great if you can add support to terraform version 0.12
Currently i am getting this error:
Error: Failed to instantiate provider "redshift" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Thanks,
Mor.

**Comment by frankfarrell** [comment]
Hmm, that's not good :) I'll need to do some research to see what has changed exactly. But if you have any links to what's changed or how other providers handle the api change please post them up!

**Comment by jml** [comment]
- [0.12 readiness for providers](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html)
- [General 0.12 announcement](https://www.hashicorp.com/blog/announcing-terraform-0-12)
- [Upgrade guide for end-users(https://www.terraform.io/upgrade-guides/0-12.html)

**Comment by Tenzer** [comment]
I have made a PR in https://github.com/frankfarrell/terraform-provider-redshift/pull/29 where I update the dependencies for this project. That seems to be the only change necessary for Terraform 0.12 support as far as I can test.

**Comment by Monkman08** [comment]
Can this be merged please

**Comment by devops-ameyer** [comment]
Was this merged? I'm getting this error.

**Comment by DevoKun** [comment]
@devops-ameyer ,

The latest release available is only compatible with terraform 0.11.
To use the redshift provider with Terraform 0.12, Download the source and compile it:

```bash
git clone git@github.com:frankfarrell/terraform-provider-redshift.git

brew install golang

export GOOS=darwin
export GOARCH=amd64
go build -o terraform-provider-redshift_v0.0.2_x5

mkdir -p ~/.terraform.d/plugins/darwin_amd64/
if [ -f ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x4 ]; then
  rm ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x4
fi

cp terraform-provider-redshift_v0.0.2_x5 ~/.terraform.d/plugins/darwin_amd64/

chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x5
```

**Comment by jasonhmichael** [comment]
Any reason the original PR from @Tenzer wasn't merged?  Thought this module was going to be my savior, but it is sadly out of date with later TF vers.

**Comment by jml** [comment]
I work with @Tenzer at Memrise. We ended up moving off Redshift in favour of BigQuery, in part because BQ is much easier to manage with Terraform specifically, and config-as-code more generally.

**Comment by DevoKun** [comment]
@jasonhmichael , are you talking about [PR#29](https://github.com/frankfarrell/terraform-provider-redshift/pull/29) ?

That pull request **was** merged.

However, a new _[release](https://github.com/frankfarrell/terraform-provider-redshift/releases)_ was never produced.

If you download and build the code it will work for you:

```bash
git clone git@github.com:frankfarrell/terraform-provider-redshift.git

brew install golang

export GOOS=darwin
export GOARCH=amd64
go build -o terraform-provider-redshift_v0.0.2_x5

mkdir -p ~/.terraform.d/plugins/darwin_amd64/
if [ -f ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x4 ]; then
  rm ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x4
fi

cp terraform-provider-redshift_v0.0.2_x5 ~/.terraform.d/plugins/darwin_amd64/

chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-redshift_v0.0.2_x5
```

**Comment by frankfarrell** [comment]
Hi there, yes sorry that PR was merged but I haven't done a build. @DevoKun 's suggestion is a good one.

**Comment by jasonhmichael** [comment]
I understand the situation - here's mine: I am wfh during the pandemic (no access to admins), don't have homebrew installed on mac, don't have admin or sudo access to do that.  Without brew, I can't get golang.
I can kick this down the road a little farther though, and won't jump through hoops to accomplish the above if you think you may be doing a build some time in the next few months.

**Comment by DevoKun** [comment]
@jasonhmichael , sorry to hear your Mac is so locked down. That's unfortunate.

You can install [go](https://golang.org/dl/) without `brew`. You can download a [`pkg`](https://golang.org/dl/) and install that outside of `brew`.

If you're willing to trust me, I have [uploaded my compiled version of `terraform-provider-redshift_v0.0.2_x5`](http://devokun.s3-website-us-east-1.amazonaws.com/terraform-provider-redshift_v0.0.2_x5.zip) which you may download.

Considering how locked down your Mac is, I would recommend that you consider setting up a Linux VM with VirtualBox where you can have free reign to do what you need.
You may also opt to setup a `t3a.nano` EC2 instance for your terraforming.

**Comment by jasonhmichael** [comment]
:) We have an ec2 container that we use for this too, but golang isn't whitelisted with our proxy.  Getting that added is also a process... its hoops all the way down.

**Comment by frankfarrell** [comment]
Hi there. Sorry to hear that, I will do a release in the morning.

**Comment by jasonhmichael** [comment]
Hey @frankfarrell - just checking in on this.  I appreciate the intent to do the release, but don't see it yet.  Just wondering if you were going to get to this soon - just planning a timeline on my end.  Thanks so much!
