### ISSUE TITLE
sslmode=disable

### ISSUE THREAD

**Issue by stephenpaulger** [frankfarrell/terraform-provider-redshift#3]
In `redshift/config.go` sslmode=disable is hard-coded.

Perhaps this should be made a configuration option so that SSL databases can be connected to.

**Comment by frankfarrell** [comment]
Good idea, options are here: https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html . 
I plan to work on this more next week and I can add then, or please open a PR in the meantime

**Comment by stephenpaulger** [comment]
I have actually just made the change to make it an option, it was fairly simple. I'll send a PR shortly.

**Comment by frankfarrell** [comment]
Closed by #4
