### ISSUE TITLE
Error while building: local import "./redshift" in non-local package

### ISSUE THREAD

**Issue by paranoidd** [frankfarrell/terraform-provider-redshift#33]
Hello!

First of all - thank you a lot for the work you are doing here!

I am coming here with a problem - I am no longer able to build provider successfully, and I am afraid I am too much of a noob to attempt fixing it myself. I baked in this provider into my organizations Terraform Docker image long time ago and it recently started to fail.

The error I encountered is:
```
src/github.com/frankfarrell/terraform-provider-redshift/main.go:4:2: local import "./redshift" in non-local package
```

Some details about my build environment:
- I am using go 1.11.5 (provided by Docker image `golang:1.11.5-alpine3.9`)
- I have been building the provider using following command: `gox -osarch="linux/amd64" -output="${HOME}/.terraform.d/plugins/{{.OS}}_{{.Arch}}/terraform-provider-redshift_v0.0.2" .`
- I have attempted simple `go build -o terraform-provider-redshift_v0.0.2` but this has failed with same error as well

Searching on Google/StackOverflow I only found posts suggesting to change the method of importing go packages - I figured it will be better to open an issue to discuss with expert, rather than try to fiddle with it on my own.

I am sorry if this issue is somehow redundant, dummy or I am ignorant by opening it - I am totally not experienced with golang (I am only building custom terraform providers using README's provided by maintainers ;-))

I hope you can point me into right direction with how to tackle this.

Thank you very much!

**Comment by Tenzer** [comment]
I had the same issue when I tried to build an updated version last time. I managed to fix it with this patch:
```patch
--- a/main.go
+++ b/main.go
@@ -1,7 +1,7 @@
 package main

 import (
-       "./redshift"
+       "github.com/frankfarrell/terraform-provider-redshift/redshift"
        "github.com/hashicorp/terraform/plugin"
        "github.com/hashicorp/terraform/terraform"
 )
```

I think using relative paths in Go imports is an old thing and probably should be replaced with this anyway, but I'll leave that up to @frankfarrell to decide.

**Comment by frankfarrell** [comment]
Thanks for opening the bug @paranoidd , and thanks for the fix @Tenzer 

Its building successfully on master now. 

Would love if you could share your docker image, or an open sourceable variant of it? 

Cheers!
